# DataSource Config
server:
  port: 8084
spring:
  application:
    name: mp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/zk_db_paper?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/zk_digital_asset?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
    level:
      root: INFO

#zkml 员工档案数据接口
zkml:
  staff:
    url: https://employee.izkml.cn/api
  car:
    url: https://car-files-sd.mlcfg.online
  luobao:
    url: https://gateway-lb.izkml.cn/report/
